"sudo apt-get install nginx -y",
"sudo pip install awscli",
"sudo yum -y install java-1.8*",
"echo java -version",
"JAVA_HOME=/usr/lib/jvm/java-1.8*",
"export JAVA_HOME",
"PATH=$PATH:$JAVA_HOME",
"sudo yum -y install wget",
"sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo",
"sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key",
"sudo yum -y install jenkins",
"echo jenkins installed",
"sudo service jenkins start",
"echo service jenkins status"
